version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'newsletter'
      MYSQL_USER: 'newsletter'
      MYSQL_PASSWORD: 'newsletter'
      MYSQL_ROOT_PASSWORD: 'newsletter'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:newsletter@newsletter_database-db-1:3306/newsletter
volumes:
  my-db:
